# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from laser_feature_extraction/CornerMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import laser_feature_extraction.msg
import geometry_msgs.msg

class CornerMsg(genpy.Message):
  _md5sum = "55a99cac39a2bb4bd0ca826dbb7a847e"
  _type = "laser_feature_extraction/CornerMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point p
float64 psi
int32 id
LineMsg l_a
LineMsg l_b

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: laser_feature_extraction/LineMsg
float64 A
float64 B
float64 C
geometry_msgs/Point p_a
geometry_msgs/Point p_b
int32 id
"""
  __slots__ = ['p','psi','id','l_a','l_b']
  _slot_types = ['geometry_msgs/Point','float64','int32','laser_feature_extraction/LineMsg','laser_feature_extraction/LineMsg']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       p,psi,id,l_a,l_b

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CornerMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.p is None:
        self.p = geometry_msgs.msg.Point()
      if self.psi is None:
        self.psi = 0.
      if self.id is None:
        self.id = 0
      if self.l_a is None:
        self.l_a = laser_feature_extraction.msg.LineMsg()
      if self.l_b is None:
        self.l_b = laser_feature_extraction.msg.LineMsg()
    else:
      self.p = geometry_msgs.msg.Point()
      self.psi = 0.
      self.id = 0
      self.l_a = laser_feature_extraction.msg.LineMsg()
      self.l_b = laser_feature_extraction.msg.LineMsg()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4di9di9di().pack(_x.p.x, _x.p.y, _x.p.z, _x.psi, _x.id, _x.l_a.A, _x.l_a.B, _x.l_a.C, _x.l_a.p_a.x, _x.l_a.p_a.y, _x.l_a.p_a.z, _x.l_a.p_b.x, _x.l_a.p_b.y, _x.l_a.p_b.z, _x.l_a.id, _x.l_b.A, _x.l_b.B, _x.l_b.C, _x.l_b.p_a.x, _x.l_b.p_a.y, _x.l_b.p_a.z, _x.l_b.p_b.x, _x.l_b.p_b.y, _x.l_b.p_b.z, _x.l_b.id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.p is None:
        self.p = geometry_msgs.msg.Point()
      if self.l_a is None:
        self.l_a = laser_feature_extraction.msg.LineMsg()
      if self.l_b is None:
        self.l_b = laser_feature_extraction.msg.LineMsg()
      end = 0
      _x = self
      start = end
      end += 188
      (_x.p.x, _x.p.y, _x.p.z, _x.psi, _x.id, _x.l_a.A, _x.l_a.B, _x.l_a.C, _x.l_a.p_a.x, _x.l_a.p_a.y, _x.l_a.p_a.z, _x.l_a.p_b.x, _x.l_a.p_b.y, _x.l_a.p_b.z, _x.l_a.id, _x.l_b.A, _x.l_b.B, _x.l_b.C, _x.l_b.p_a.x, _x.l_b.p_a.y, _x.l_b.p_a.z, _x.l_b.p_b.x, _x.l_b.p_b.y, _x.l_b.p_b.z, _x.l_b.id,) = _get_struct_4di9di9di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4di9di9di().pack(_x.p.x, _x.p.y, _x.p.z, _x.psi, _x.id, _x.l_a.A, _x.l_a.B, _x.l_a.C, _x.l_a.p_a.x, _x.l_a.p_a.y, _x.l_a.p_a.z, _x.l_a.p_b.x, _x.l_a.p_b.y, _x.l_a.p_b.z, _x.l_a.id, _x.l_b.A, _x.l_b.B, _x.l_b.C, _x.l_b.p_a.x, _x.l_b.p_a.y, _x.l_b.p_a.z, _x.l_b.p_b.x, _x.l_b.p_b.y, _x.l_b.p_b.z, _x.l_b.id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.p is None:
        self.p = geometry_msgs.msg.Point()
      if self.l_a is None:
        self.l_a = laser_feature_extraction.msg.LineMsg()
      if self.l_b is None:
        self.l_b = laser_feature_extraction.msg.LineMsg()
      end = 0
      _x = self
      start = end
      end += 188
      (_x.p.x, _x.p.y, _x.p.z, _x.psi, _x.id, _x.l_a.A, _x.l_a.B, _x.l_a.C, _x.l_a.p_a.x, _x.l_a.p_a.y, _x.l_a.p_a.z, _x.l_a.p_b.x, _x.l_a.p_b.y, _x.l_a.p_b.z, _x.l_a.id, _x.l_b.A, _x.l_b.B, _x.l_b.C, _x.l_b.p_a.x, _x.l_b.p_a.y, _x.l_b.p_a.z, _x.l_b.p_b.x, _x.l_b.p_b.y, _x.l_b.p_b.z, _x.l_b.id,) = _get_struct_4di9di9di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4di9di9di = None
def _get_struct_4di9di9di():
    global _struct_4di9di9di
    if _struct_4di9di9di is None:
        _struct_4di9di9di = struct.Struct("<4di9di9di")
    return _struct_4di9di9di
