// Generated by gencpp from file laser_feature_extraction/DepthFeatures.msg
// DO NOT EDIT!


#ifndef LASER_FEATURE_EXTRACTION_MESSAGE_DEPTHFEATURES_H
#define LASER_FEATURE_EXTRACTION_MESSAGE_DEPTHFEATURES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <laser_feature_extraction/LineMsg.h>
#include <laser_feature_extraction/CornerMsg.h>

namespace laser_feature_extraction
{
template <class ContainerAllocator>
struct DepthFeatures_
{
  typedef DepthFeatures_<ContainerAllocator> Type;

  DepthFeatures_()
    : header()
    , lines()
    , corners()  {
    }
  DepthFeatures_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lines(_alloc)
    , corners(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::laser_feature_extraction::LineMsg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::laser_feature_extraction::LineMsg_<ContainerAllocator> >::other >  _lines_type;
  _lines_type lines;

   typedef std::vector< ::laser_feature_extraction::CornerMsg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::laser_feature_extraction::CornerMsg_<ContainerAllocator> >::other >  _corners_type;
  _corners_type corners;





  typedef boost::shared_ptr< ::laser_feature_extraction::DepthFeatures_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laser_feature_extraction::DepthFeatures_<ContainerAllocator> const> ConstPtr;

}; // struct DepthFeatures_

typedef ::laser_feature_extraction::DepthFeatures_<std::allocator<void> > DepthFeatures;

typedef boost::shared_ptr< ::laser_feature_extraction::DepthFeatures > DepthFeaturesPtr;
typedef boost::shared_ptr< ::laser_feature_extraction::DepthFeatures const> DepthFeaturesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::laser_feature_extraction::DepthFeatures_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::laser_feature_extraction::DepthFeatures_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace laser_feature_extraction

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'laser_feature_extraction': ['/home/turtlebot/ros_workspace/src/laser_feature_extraction/msg'], 'visualization_msgs': ['/opt/ros/melodic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::laser_feature_extraction::DepthFeatures_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser_feature_extraction::DepthFeatures_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_feature_extraction::DepthFeatures_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_feature_extraction::DepthFeatures_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_feature_extraction::DepthFeatures_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_feature_extraction::DepthFeatures_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::laser_feature_extraction::DepthFeatures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de670e06a19a9ce51ae28733a6732dd1";
  }

  static const char* value(const ::laser_feature_extraction::DepthFeatures_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xde670e06a19a9ce5ULL;
  static const uint64_t static_value2 = 0x1ae28733a6732dd1ULL;
};

template<class ContainerAllocator>
struct DataType< ::laser_feature_extraction::DepthFeatures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "laser_feature_extraction/DepthFeatures";
  }

  static const char* value(const ::laser_feature_extraction::DepthFeatures_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::laser_feature_extraction::DepthFeatures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
LineMsg[] lines\n\
CornerMsg[] corners\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: laser_feature_extraction/LineMsg\n\
float64 A\n\
float64 B\n\
float64 C\n\
geometry_msgs/Point p_a\n\
geometry_msgs/Point p_b\n\
int32 id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: laser_feature_extraction/CornerMsg\n\
geometry_msgs/Point p\n\
float64 psi\n\
int32 id\n\
LineMsg l_a\n\
LineMsg l_b\n\
";
  }

  static const char* value(const ::laser_feature_extraction::DepthFeatures_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::laser_feature_extraction::DepthFeatures_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lines);
      stream.next(m.corners);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DepthFeatures_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laser_feature_extraction::DepthFeatures_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::laser_feature_extraction::DepthFeatures_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lines[]" << std::endl;
    for (size_t i = 0; i < v.lines.size(); ++i)
    {
      s << indent << "  lines[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::laser_feature_extraction::LineMsg_<ContainerAllocator> >::stream(s, indent + "    ", v.lines[i]);
    }
    s << indent << "corners[]" << std::endl;
    for (size_t i = 0; i < v.corners.size(); ++i)
    {
      s << indent << "  corners[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::laser_feature_extraction::CornerMsg_<ContainerAllocator> >::stream(s, indent + "    ", v.corners[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASER_FEATURE_EXTRACTION_MESSAGE_DEPTHFEATURES_H
